In [2]:
f1=open('bing.txt','r')
f2=open('fang.txt','r')

line1=f1.readlines()
line2=f2.readlines()
bi=[]
for line in line1:
    line=line.replace('\n','')
    x=line.split(' ')
    bi.append(x)


fa=[]
for line in line2:
    line=line.replace('\n','')
    x=line.split(' ')
    fa.append(x)


import numpy as np

bi_a=np.array(bi)

fa_a=np.array(fa)


label1=bi_a[:,0]


fe1=bi_a[:,1:]
fe1= fe1.astype(np.float64)
label1= label1.astype(np.int)


label2=fa_a[:,0]
fe2=fa_a[:,1:]
fe2= fe2.astype(np.float64)
label2= label2.astype(np.int)


from sklearn.model_selection import train_test_split

train_X,test_X, train_y, test_y = train_test_split(fe1,label1,test_size=0.2)
print(test_y)

[ 585 1776  568 2992 1841 2458 3625 2674 2207 1750 3526 1514 1639 3469
 3311 1935 3242 1629 3426  261  555  911 2671  716 2191 3148 1415 3233
 1320  447  925 2770 2165 3515  619 2754 2724 1859 1133  946 3381  796
 1073 1122 2512 1433 2579 2059 1828 2737 1511 2035 2819   89 2378 2706
 2382  873  316 3627 2917 2804 1561  782  894 3075  384  368 2256 1349
 2092  302 2870 2791 3159 1467  610  787 2743  599 3123 2087 1259  307
  747 2643 3561 2574  404  530 1257]


In [10]:
from math import sqrt

def knn(x,k):
    dis=[sqrt(np.sum((g-x)**2))for g in fe2]
    nearest=np.argsort(dis)
    topK_k=[label2[i] for i in nearest[:k]]
    #print(topK_k)
    p=0
    ans =[]
    print('匹配的药方如下：')
    print(nearest)
    for h in nearest[:k]:
        print(topK_k[p],'欧式距离是：',dis[h])
        ans.append(topK_k[p])
        p = p + 1
    return ans


In [11]:
err=0
predicted =[]
j=0
ll=list(fe2)
te=list(test_X)
ty=list(test_y)
f4=open('graph_edges_bing-fang-relation.txt','r')

dic={}
all1=[]
set1=set()
set2=set()
lines=f4.readlines()
for line in lines:
    line=line.replace('\n','')
    x=line.split(' ')
    set1.add(x[0])
    set2.add(x[1])
    all1.append(x)
print(len(set1))
print(len(set2))


for k in set2:
    v=[]
    for i in all1:
        if k in i:
            v.append(i[0])
    dic[k]=v
j=0
test_X=list(test_X)
ri=0
for x in test_X:
    print('*************',j,'*************')
    print(test_y[j])
    ans=knn(x,15)
    # fang=[]
    fang=dic.get(str(test_y[j]))
    fang=list(map(int,fang))
    print('该病对应的全部药方是：',fang)
    print('推荐的全部药方是：',ans)
    ins=list(set(fang).intersection(set(ans)))

    if(len(ins)!=0):
        ri=ri+1
    j=j+1
print("test 个数为：",len(test_X))
print("hit 个数为：",ri)
print("命中率为：",ri/len(test_X))

1709
451
************* 0 *************
585
匹配的药方如下：
[1706 1639 1651 ... 1474 1479 1491]
1702 欧式距离是： 2.1608625721984462
2230 欧式距离是： 2.190368468433446
2529 欧式距离是： 2.3385211018995236
3560 欧式距离是： 2.339002601000853
2385 欧式距离是： 2.3523658370522527
2001 欧式距离是： 2.3619895894289757
2499 欧式距离是： 2.3646474745587427
2189 欧式距离是： 2.380909292635762
584 欧式距离是： 2.4192492852937932
1684 欧式距离是： 2.4268085990656285
1632 欧式距离是： 2.428610703264772
1138 欧式距离是： 2.4297180484812926
3096 欧式距离是： 2.4302676276827544
2119 欧式距离是： 2.441062167100148
2511 欧式距离是： 2.4443942445755606
该病对应的全部药方是： [584]
推荐的全部药方是： [1702, 2230, 2529, 3560, 2385, 2001, 2499, 2189, 584, 1684, 1632, 1138, 3096, 2119, 2511]
************* 1 *************
1776
匹配的药方如下：
[1702 1708 1664 ... 1500 1491 1479]
3013 欧式距离是： 2.3320246340615802
2001 欧式距离是： 2.380220629297687
699 欧式距离是： 2.3816557287169995
1267 欧式距离是： 2.4603195464922654
487 欧式距离是： 2.474417853628272
2385 欧式距离是： 2.481244806181047
2736 欧式距离是： 2.485594118463765
3448 欧式距离是： 2.5092963499120438
2771 欧式距离是： 2

2670 欧式距离是： 2.33122749782843
454 欧式距离是： 2.440535440910378
3069 欧式距离是： 2.450992065249036
1267 欧式距离是： 2.4557692764537906
1634 欧式距离是： 2.4747479369364767
2385 欧式距离是： 2.4795543578655854
1702 欧式距离是： 2.490299302798932
2771 欧式距离是： 2.4975802901281243
2876 欧式距离是： 2.498394260249406
2119 欧式距离是： 2.515967574573044
3560 欧式距离是： 2.5420116770230345
1523 欧式距离是： 2.5556554048303686
738 欧式距离是： 2.556521255002548
2736 欧式距离是： 2.5647557297117833
3101 欧式距离是： 2.572973308986469
该病对应的全部药方是： [2670]
推荐的全部药方是： [2670, 454, 3069, 1267, 1634, 2385, 1702, 2771, 2876, 2119, 3560, 1523, 738, 2736, 3101]
************* 23 *************
716
匹配的药方如下：
[1693 1690 1616 ... 1493 1479 1491]
2876 欧式距离是： 2.1373443028682826
3069 欧式距离是： 2.262596063348993
1634 欧式距离是： 2.273165629126775
3577 欧式距离是： 2.2815286904994085
1267 欧式距离是： 2.406868253407158
2230 欧式距离是： 2.4249687849989408
2511 欧式距离是： 2.4368665393966844
454 欧式距离是： 2.456703176537044
1702 欧式距离是： 2.5027886239657575
2484 欧式距离是： 2.531047145893499
487 欧式距离是： 2.533434292137515
1632 欧式距离是： 2.5

匹配的药方如下：
[1682 1677 1617 ... 1479 1474 1491]
1632 欧式距离是： 2.385496036149856
2511 欧式距离是： 2.485439418941369
2385 欧式距离是： 2.5585930448140575
3069 欧式距离是： 2.6263902273776494
3448 欧式距离是： 2.627675646131179
2587 欧式距离是： 2.6360071098858127
59 欧式距离是： 2.6371814220032044
2499 欧式距离是： 2.650451691442653
2578 欧式距离是： 2.6538671977294483
3096 欧式距离是： 2.6621722957420757
487 欧式距离是： 2.663133726720787
3560 欧式距离是： 2.66822575362403
1702 欧式距离是： 2.6743420908246396
1267 欧式距离是： 2.6967869460560467
3013 欧式距离是： 2.7026949745267186
该病对应的全部药方是： [2578, 2667]
推荐的全部药方是： [1632, 2511, 2385, 3069, 3448, 2587, 59, 2499, 2578, 3096, 487, 3560, 1702, 1267, 3013]
************* 47 *************
2059
匹配的药方如下：
[1673 1658 1606 ... 1474 1494 1479]
487 欧式距离是： 2.148472173531338
222 欧式距离是： 2.36391561963575
1267 欧式距离是： 2.3915798002241253
2058 欧式距离是： 2.3926485414585454
2499 欧式距离是： 2.4037093924657698
1702 欧式距离是： 2.4161887188168523
3069 欧式距离是： 2.4193440335391667
2587 欧式距离是： 2.4415389407338832
2111 欧式距离是： 2.4431183085036166
1983 欧式距离是： 2.49367738

3392 欧式距离是： 3.2740674362532736
1941 欧式距离是： 3.297393734633244
82 欧式距离是： 3.298027449446516
2303 欧式距离是： 3.309258880183436
2713 欧式距离是： 3.3123650428633664
1028 欧式距离是： 3.3228369497487176
2542 欧式距离是： 3.3435679667709586
653 欧式距离是： 3.3463160901248044
该病对应的全部药方是： [367]
推荐的全部药方是： [367, 3345, 1704, 1528, 1198, 3344, 2701, 3392, 1941, 82, 2303, 2713, 1028, 2542, 653]
************* 68 *************
2256
匹配的药方如下：
[1205 1587 1675 ... 1494 1474 1479]
2255 欧式距离是： 2.1139932830995942
3101 欧式距离是： 2.2606545669060325
1300 欧式距离是： 2.407009050198514
2587 欧式距离是： 2.4648786581101763
2119 欧式距离是： 2.4885344730765206
1632 欧式距离是： 2.51422418331094
59 欧式距离是： 2.5691210791594985
1702 欧式距离是： 2.620274041932033
222 欧式距离是： 2.643968556055371
3069 欧式距离是： 2.644471239462534
3577 欧式距离是： 2.658123645316362
2499 欧式距离是： 2.6775489562918398
3560 欧式距离是： 2.6889852568033557
2001 欧式距离是： 2.6915476628887247
3448 欧式距离是： 2.708093606696282
该病对应的全部药方是： [2255]
推荐的全部药方是： [2255, 3101, 1300, 2587, 2119, 1632, 59, 1702, 222, 3069, 3577, 2499, 3560, 200

2550 欧式距离是： 2.7422053496750727
2854 欧式距离是： 2.77287942888709
2111 欧式距离是： 2.8523445206104454
3577 欧式距离是： 2.855473304713558
3448 欧式距离是： 2.8776864128636337
3013 欧式距离是： 2.882847596044705
1634 欧式距离是： 2.8834774928069655
3024 欧式距离是： 2.8980683551074895
2230 欧式距离是： 2.912976099699749
2047 欧式距离是： 2.919158104073487
699 欧式距离是： 2.9364458477339994
该病对应的全部药方是： [403, 1622, 1655, 2054, 2550, 2788, 2854]
推荐的全部药方是： [1655, 1622, 2788, 403, 2550, 2854, 2111, 3577, 3448, 3013, 1634, 3024, 2230, 2047, 699]
************* 89 *************
530
匹配的药方如下：
[1628 1591 1659 ... 1474 1479 1491]
2833 欧式距离是： 1.3548694640589256
529 欧式距离是： 1.3687170222460996
3577 欧式距离是： 2.0153168518361855
2230 欧式距离是： 2.0824394942063025
1684 欧式距离是： 2.0920718860121035
1138 欧式距离是： 2.092849737142922
1634 欧式距离是： 2.1130189336661025
699 欧式距离是： 2.1238321501104056
2888 欧式距离是： 2.1245622097528662
3024 欧式距离是： 2.1397512204233666
1704 欧式距离是： 2.140058406735328
3339 欧式距离是： 2.159265981264523
3013 欧式距离是： 2.1861476856764526
3096 欧式距离是： 2.187544792627673
2499 